title: Adinda Tsabita Salma # your name (or website title) here
logo: "/images/Pasfoto (1).jpg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A third year undergraduate student at the Faculty of Economics and Business Universitas Airlangga majoring in Development Economics. With some previous organizational and work experience. Have a high curiosity about new things, highly motivated, eager to learn, responsible, responsive and adaptable person. 
  <br><br>
  <a href="https://www.linkedin.com/in/adindatsabita/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
